encoding: utf-8
exclude: [".gitignore", "Gemfile", "Gemfile.lock", "LICENSE", "README.md"]
paginate: 6
paginate_path: /page/:num/
permalink: /:categories/:title/
icon: /img/icon.png
thumbnail: /img/logo-ogp.png
sass:
  style: compressed
gems:
  - jekyll-paginate
timezone: America/New_York
excerpt_separator: <!--more-->

color:
  default: "dark-green"
  accent: "yellow"


title: Napier Garden Motel
keywords: "cheap accomodation in Napier, family motel, parking hotel"
author:
  name: "Ben Fraser"
  twitter: napiergardenmotel

protocol: https
url: napiergardenmotel.github.io
baseurl: "/jekyll-materialize"

# Google Analytics
tracking_id: UA-80302740-1
